### FETCH A COURSE ON THE BASED ON SLUG
GET http://localhost:3000/api/courses/web-development-masterclass

### CREATE A NEW COURSE
POST http://localhost:3000/api/courses


### FETCH COURSE ON THE BASED ON TOPIC SLUG

GET http://localhost:3000/api/topics/marketing